export type SofiaSourceStatus={id:string;label:string;url:string;status:"ok"|"error"|"fallback";checkedAt:string;detail?:string};
export type SofiaInstitutionCategory="ДГ"|"Детска градина с яслени групи"|"Ясла"|"Училище с подготвителни групи";
export type SofiaInstitution={id:string;name:string;type:"nursery"|"kindergarten"|"school"|"unknown";category?:SofiaInstitutionCategory;subtype?:string;district?:string;districtCode?:string;address?:string;website?:string;phone?:string;email?:string;source:string;sourceUrl:string;raw?:Record<string,unknown>};
export type SofiaCatalog={generatedAt:string;districts:string[];years:string[];categories:SofiaInstitutionCategory[];institutions:SofiaInstitution[];groupedByDistrict:Record<string,Record<string,SofiaInstitution[]>>;sources:SofiaSourceStatus[];stats:{institutionsTotal:number;districtsTotal:number;byCategory:Record<string,number>;byType:Record<string,number>};notes:string[]};

type Feature={properties?:Record<string,unknown>};
type GeoJson={features?:Feature[]};

export const SOFIA_DISTRICTS=["Банкя","Витоша","Връбница","Възраждане","Изгрев","Илинден","Искър","Красна поляна","Красно село","Кремиковци","Лозенец","Люлин","Младост","Надежда","Нови Искър","Оборище","Овча купел","Панчарево","Подуяне","Сердика","Слатина","Средец","Студентски","Триадица"];
export const SOFIA_DISTRICT_CODES:Record<string,string>={"01":"Средец","02":"Красно село","03":"Възраждане","04":"Оборище","05":"Сердика","06":"Подуяне","07":"Слатина","08":"Изгрев","09":"Лозенец","10":"Триадица","11":"Красна поляна","12":"Илинден","13":"Надежда","14":"Искър","15":"Младост","16":"Студентски","17":"Витоша","18":"Овча купел","19":"Люлин","20":"Връбница","21":"Нови Искър","22":"Кремиковци","23":"Панчарево","24":"Банкя"};
export const OFFICIAL_SOURCE_URLS={kgHome:"https://kg.sofia.bg/#/home",kgSpots:"https://kg.sofia.bg/#/spots",kgKindergartens:"https://kg.sofia.bg/#/kindergartens",sofiaPlanApi:"https://api.sofiaplan.bg",sofiaPlanDatasets:"https://api.sofiaplan.bg/datasets",sofiaPlanKindergartens:"https://api.sofiaplan.bg/datasets/142",sofiaPlanMunicipalKindergartens:"https://api.sofiaplan.bg/datasets/311",sofiaPlanSchools:"https://api.sofiaplan.bg/datasets/166",sofiaPlanDistricts:"https://api.sofiaplan.bg/datasets/628",sofiaKindergartenRegister:"https://www.sofia.bg/kinder-garden",sofiaAdmissionService:"https://www.sofia.bg/web/svc/w/priem-v-detski-zavedenia"};

const CATEGORIES:SofiaInstitutionCategory[]=["ДГ","Детска градина с яслени групи","Ясла","Училище с подготвителни групи"];
const FALLBACK_INSTITUTIONS:SofiaInstitution[]=[{id:"fallback-catalog",name:"Каталогът временно не е зареден",type:"unknown",category:"ДГ",district:"Средец",source:"fallback",sourceUrl:OFFICIAL_SOURCE_URLS.sofiaPlanApi}];

function slugify(value:string){return value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-+|-+$/g,"").slice(0,90)}
function asString(value:unknown){if(typeof value==="string")return value.trim()||undefined;if(typeof value==="number")return String(value);return undefined}
function code(value:unknown){const raw=asString(value);return raw?raw.padStart(2,"0"):undefined}
export function getCatalogYears(now=new Date()){const currentYear=now.getFullYear();const years:string[]=[];for(let year=currentYear;year>=currentYear-6;year-=1)years.push(String(year));return years}

function isPrivateKindergarten(record:Record<string,unknown>){const typeCode=asString(record.type)??asString(record.tip);const name=(asString(record.object_nam)??asString(record.ime)??"").toLowerCase();const ownership=(asString(record.ownership)??asString(record.vid_sobstvenost)??asString(record.sobstvenost)??asString(record.forma)??"").toLowerCase();return typeCode==="3"||ownership.includes("част")||name.includes("частна")||name.includes("чдг")||name.includes("чдясла")||name.includes("чя")}
function classifyKindergarten(record:Record<string,unknown>):Pick<SofiaInstitution,"type"|"category"|"subtype">{const name=asString(record.object_nam)??asString(record.ime)??"";const t=asString(record.type)??asString(record.tip);const lower=name.toLowerCase();if(t==="2"||lower.includes("сдя")||/^д[яа]\s*№/i.test(name))return{type:"nursery",category:"Ясла",subtype:"independent_nursery"};if(t==="4")return{type:"kindergarten",category:"Детска градина с яслени групи",subtype:"kindergarten_with_nursery_groups"};return{type:"kindergarten",category:"ДГ",subtype:"kindergarten"}}
function normalizeKindergarten(record:Record<string,unknown>,index:number):SofiaInstitution|null{const name=asString(record.object_nam)??asString(record.ime);if(!name||isPrivateKindergarten(record))return null;const districtCode=code(record.kod_rayon);const classification=classifyKindergarten(record);return{id:`${classification.subtype}-${districtCode??"unknown"}-${slugify(name)}-${asString(record.id)??index}`,name,...classification,district:districtCode?SOFIA_DISTRICT_CODES[districtCode]:undefined,districtCode,address:asString(record.adres),website:asString(record.website),phone:asString(record.telefon),email:asString(record.email),source:"sofiaplan.municipal_kindergarten_points",sourceUrl:OFFICIAL_SOURCE_URLS.sofiaPlanMunicipalKindergartens,raw:record}}
function normalizeSchool(record:Record<string,unknown>,index:number):SofiaInstitution|null{const name=asString(record.object_nam)??asString(record.ime);if(!name)return null;const t=asString(record.type)??asString(record.tip);if(t!=="1"&&t!=="2")return null;const districtCode=code(record.kod_rayon);return{id:`school-preparatory-${districtCode??"unknown"}-${slugify(name)}-${asString(record.id)??index}`,name,type:"school",category:"Училище с подготвителни групи",subtype:"school_with_preparatory_groups",district:districtCode?SOFIA_DISTRICT_CODES[districtCode]:undefined,districtCode,address:asString(record.adres),source:"sofiaplan.school_points",sourceUrl:OFFICIAL_SOURCE_URLS.sofiaPlanSchools,raw:record}}

async function fetchGeoJson(url:string,checkedAt:string):Promise<{source:SofiaSourceStatus;features:Feature[]}>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8500);try{const response=await fetch(url,{signal:controller.signal,headers:{accept:"application/geo+json,application/json,text/plain,*/*","user-agent":"MZM Sofia catalog sync"},next:{revalidate:60*60*24}});const text=await response.text();if(!response.ok)throw new Error(`HTTP ${response.status}`);const parsed=JSON.parse(text) as GeoJson;const features=Array.isArray(parsed.features)?parsed.features:[];return{features,source:{id:`sofiaplan-${url.split("/").pop()}`,label:`SofiaPlan API — ${url}`,url,status:"ok",checkedAt,detail:`Loaded ${features.length} features.`}}}catch(error){return{features:[],source:{id:`sofiaplan-${url.split("/").pop()}`,label:`SofiaPlan API — ${url}`,url,status:"error",checkedAt,detail:error instanceof Error?error.message:"Unknown SofiaPlan error"}}}finally{clearTimeout(timeout)}}
function dedupe(institutions:SofiaInstitution[]){const seen=new Map<string,SofiaInstitution>();for(const item of institutions){const key=`${item.type}|${item.district??""}|${item.name.toLowerCase()}|${item.address??""}`;if(!seen.has(key))seen.set(key,item)}return Array.from(seen.values()).sort((a,b)=>`${a.districtCode??"99"}-${a.category??""}-${a.name}`.localeCompare(`${b.districtCode??"99"}-${b.category??""}-${b.name}`,"bg"))}
function groupByDistrict(institutions:SofiaInstitution[]){return institutions.reduce<Record<string,Record<string,SofiaInstitution[]>>>((acc,item)=>{const district=item.district??"Без район";const category=item.category??item.type;acc[district]??={};acc[district][category]??=[];acc[district][category].push(item);return acc},{})}
function stats(institutions:SofiaInstitution[]):SofiaCatalog["stats"]{return institutions.reduce<SofiaCatalog["stats"]>((s,item)=>{s.institutionsTotal+=1;s.byCategory[item.category??item.type]=(s.byCategory[item.category??item.type]??0)+1;s.byType[item.type]=(s.byType[item.type]??0)+1;return s},{institutionsTotal:0,districtsTotal:SOFIA_DISTRICTS.length,byCategory:{},byType:{}})}

export async function getSofiaCatalog():Promise<SofiaCatalog>{const checkedAt=new Date().toISOString();const[kindergartens,schools]=await Promise.all([fetchGeoJson(OFFICIAL_SOURCE_URLS.sofiaPlanMunicipalKindergartens,checkedAt),fetchGeoJson(OFFICIAL_SOURCE_URLS.sofiaPlanSchools,checkedAt)]);const live=dedupe([...kindergartens.features.map((f,i)=>normalizeKindergarten(f.properties??{},i)).filter((x):x is SofiaInstitution=>Boolean(x)),...schools.features.map((f,i)=>normalizeSchool(f.properties??{},i)).filter((x):x is SofiaInstitution=>Boolean(x))]);const institutions=live.length?live:FALLBACK_INSTITUTIONS;return{generatedAt:checkedAt,districts:SOFIA_DISTRICTS,years:getCatalogYears(),categories:CATEGORIES,institutions,groupedByDistrict:groupByDistrict(institutions),sources:[kindergartens.source,schools.source,{id:"kg-sofia",label:"kg.sofia.bg — официален родителски интерфейс",url:OFFICIAL_SOURCE_URLS.kgHome,status:"ok",checkedAt,detail:"Catalog data is normalized through SofiaPlan public API."},...(live.length?[]:[{id:"fallback-catalog",label:"Fallback каталог",url:OFFICIAL_SOURCE_URLS.sofiaPlanApi,status:"fallback" as const,checkedAt,detail:"SofiaPlan API did not return usable records."}])],stats:stats(institutions),notes:["Каталогът се зарежда директно от публичното API на SofiaPlan.","За ДГ/ясли се използва общинският SofiaPlan dataset /datasets/311, за да не се показват частни детски градини и частни ясли.","Частните записи се филтрират допълнително по тип/име/собственост, ако попаднат в източника.","Училищата се зареждат от /datasets/166.","При срив на външното API приложението връща fallback, за да не падне UI."]}}
