import type { PlaygroundSnapshot } from "@/lib/playground";
import type { Chat } from "../types";
import { AppSection, Bubble, PageTitle, SafetyNote } from "../shared/ui";

export function ChatScreen({ activeMatch, allConfirmed, matchIsClosed, availableChats, selectedChat, selectedChatId, setSelectedChatId, snapshot, selectedProfileId, selectedUserName, userById, chatTitle, messageBody, setMessageBody, sendMessage, loading }: { activeMatch?: PlaygroundSnapshot["matches"][number]; allConfirmed: boolean; matchIsClosed: boolean; availableChats: Chat[]; selectedChat?: Chat; selectedChatId: string; setSelectedChatId: (id: string) => void; snapshot: PlaygroundSnapshot | null; selectedProfileId: string; selectedUserName: string; userById: Map<string, PlaygroundSnapshot["users"][number]>; chatTitle: (chat: Chat) => string; messageBody: string; setMessageBody: (value: string) => void; sendMessage: () => void; loading: boolean }) {
  if (!activeMatch || !allConfirmed || matchIsClosed) {
    return <AppSection><PageTitle eyebrow="Чатове" title="Още са заключени" body="Чатовете се появяват само след потвърждение от всички страни." /><SafetyNote /></AppSection>;
  }

  return <AppSection><PageTitle eyebrow="Чатове" title={selectedChat ? chatTitle(selectedChat) : "Координация"} body="При 2 страни показваме само личния чат. При 3/4 има групов и лични чатове." /><section className="rounded-[2.2rem] bg-white/90 p-4 shadow-soft backdrop-blur">{availableChats.length ? <div className="flex gap-2 overflow-x-auto pb-1">{availableChats.map((c) => <button key={c.id} type="button" onClick={() => setSelectedChatId(c.id)} className={`shrink-0 rounded-full px-4 py-3 text-xs font-extrabold ${selectedChatId === c.id ? "bg-orange text-white" : "bg-paper"}`}>{chatTitle(c)}</button>)}</div> : <p className="text-sm text-ink/50">Няма активни чатове.</p>}<div className="mt-5 space-y-3">{snapshot?.messages.filter((m) => selectedChat && m.chat_id === selectedChat.id).map((m) => { const mine = m.sender_user_id === selectedProfileId; return <Bubble key={m.id} mine={mine} name={mine ? "Ти" : userById.get(m.sender_user_id)?.display_name ?? "Родител"} body={m.body} />; })}</div>{selectedChat ? <div className="mt-5 space-y-2"><textarea value={messageBody} onChange={(e) => setMessageBody(e.target.value)} className="min-h-24 w-full rounded-[1.6rem] border-0 bg-paper p-4 text-sm outline-none" /><button type="button" disabled={loading || selectedChat.status !== "active"} onClick={sendMessage} className="w-full rounded-full bg-orange px-4 py-4 text-sm font-extrabold text-white disabled:opacity-30">Изпрати като {selectedUserName}</button></div> : null}</section><SafetyNote /></AppSection>;
}
