import type { AppTab } from "../types";
import { AppSection, RouteMark } from "../shared/ui";

function StatCard({ number, title, body, tone }: { number: string; title: string; body: string; tone: string }) {
  return <div className={`rounded-[1.8rem] ${tone} p-4 shadow-soft`}><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/65 text-lg font-extrabold">{number}</span><h3 className="mt-5 text-lg font-extrabold tracking-[-0.03em]">{title}</h3><p className="mt-2 text-xs font-semibold leading-5 text-ink/55">{body}</p></div>;
}

function InsightCard({ category, title, body, tone }: { category: string; title: string; body: string; tone: string }) {
  return <article className={`relative overflow-hidden rounded-[2rem] ${tone} p-5 shadow-soft`}><RouteMark className="absolute -right-8 -top-7 h-28 w-28 opacity-15" /><div className="relative z-10"><div className="mb-5 flex items-center justify-between"><span className="rounded-full bg-white/60 px-3 py-1.5 text-xs font-extrabold">{category}</span><span className="rounded-full bg-white/60 px-3 py-1.5 text-xs font-bold">3 мин.</span></div><h3 className="text-xl font-extrabold leading-tight tracking-[-0.03em]">{title}</h3><p className="mt-3 text-sm font-semibold leading-6 text-ink/58">{body}</p></div></article>;
}

function HeroSearch({ setTab, activeRequestText, matchCount }: { setTab: (tab: AppTab) => void; activeRequestText: string; matchCount: number }) {
  return <section className="relative overflow-hidden rounded-[2rem] bg-[#FFF0E3] p-5 shadow-soft"><RouteMark className="absolute -right-8 -top-10 h-36 w-36 opacity-15" /><div className="relative z-10 flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-ink/50">Твоят маршрут</p><h1 className="mt-1 text-4xl font-extrabold leading-[0.95] tracking-[-0.055em]">Намери <span className="text-orange">място</span></h1><p className="mt-2 text-sm font-medium leading-5 text-ink/60">за възможна координация между родители</p></div><div className="relative grid h-24 w-24 shrink-0 place-items-center rounded-[1.8rem] bg-white/65 shadow-soft"><div className="grid h-16 w-16 place-items-center rounded-full bg-lime text-xl">⌁</div></div></div><div className="relative z-10 mt-5 flex items-center gap-2 rounded-full bg-white/85 p-2 shadow-[inset_0_0_0_1px_rgba(28,27,25,0.04)]"><button className="grid h-12 w-12 place-items-center rounded-full bg-orange text-xl text-white shadow-soft">⌖</button><button className="grid h-12 w-12 place-items-center rounded-full bg-paper text-lg text-ink/60">⌕</button><button onClick={() => setTab("requests")} className="flex min-h-12 flex-1 items-center justify-between rounded-full bg-paper px-5 text-left text-sm font-bold text-ink/55">Пусни заявка <span className="text-xl text-orange">›</span></button></div><div className="relative z-10 mt-5 grid grid-cols-2 gap-3"><StatCard number={activeRequestText ? "01" : "00"} title="Активна заявка" body={activeRequestText || "Няма активна заявка"} tone="bg-lime" /><StatCard number={String(matchCount).padStart(2, "0")} title="Потенциални маршрута" body="2/3/4-странни цикли" tone="bg-[#D2E4E2]" /></div></section>;
}

export function HomeScreen({ setTab, activeRequestText, matchCount }: { setTab: (tab: AppTab) => void; activeRequestText: string; matchCount: number }) {
  return <AppSection><HeroSearch setTab={setTab} activeRequestText={activeRequestText} matchCount={matchCount} /><section className="space-y-3"><div className="flex items-center justify-between px-1"><h2 className="text-2xl font-extrabold tracking-[-0.04em]">За теб днес</h2><button className="rounded-full bg-white/80 px-4 py-2 text-xs font-bold shadow-soft">Виж всички</button></div><InsightCard category="Безопасност" title="Преди да пишеш на други родители" body="Не споделяй ЕГН, документи или данни на детето в чата. Координацията е само информативна." tone="bg-[#ECECC7]" /><InsightCard category="Важно за match" title="Типът място трябва да съвпада" body="Общ ред, СОП, хронични заболявания и социални критерии не се смесват в един цикъл." tone="bg-[#DED1E8]" /></section></AppSection>;
}
