"use client";

import { useState } from "react";
import type { PlaygroundSnapshot } from "@/lib/playground";
import { AppSection, EmptyCard, FieldLabel, PageTitle, SelectField } from "../shared/ui";
import { placeTypes } from "../types";

function PlaceTypeSelector({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <div className="mt-4 rounded-[1.8rem] bg-[#F7F5EF] p-3"><p className="px-2 text-[10px] font-extrabold uppercase tracking-[0.2em] text-ink/35">Тип място</p><div className="mt-3 grid grid-cols-2 gap-2">{placeTypes.map((type) => <button key={type} type="button" onClick={() => onChange(type)} className={`rounded-2xl px-3 py-3 text-left text-xs font-extrabold ${value === type ? "bg-orange text-white" : "bg-white/75"}`}>{type}</button>)}</div></div>;
}

function RequestCard({ text, ageGroup, active, locked, placeType, onDeactivate, onDelete, loading }: { text: string; ageGroup: string; active: boolean; locked: boolean; placeType: string; onDeactivate: () => void; onDelete: () => void; loading: boolean }) {
  return <div className="rounded-[2rem] bg-[#ECECC7] p-5 shadow-soft"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-ink/40">{active ? "Активна" : "Неактивна"} · {placeType}</p><h3 className="mt-2 text-xl font-extrabold leading-tight">{text}</h3><p className="mt-2 text-sm font-semibold text-ink/55">Набор {ageGroup}</p></div><span className="rounded-full bg-white/65 px-3 py-2 text-xs font-extrabold">{locked ? "MATCH" : "ON"}</span></div><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" disabled={loading || !active} onClick={onDeactivate} className="rounded-full bg-white/65 px-4 py-3 text-xs font-extrabold disabled:opacity-30">Деактивирай</button><button type="button" disabled={loading || locked} onClick={onDelete} className="rounded-full bg-ink px-4 py-3 text-xs font-extrabold text-white disabled:opacity-30">Изтрий</button></div></div>;
}

export function RequestScreen({ snapshot, selectedProfileId, selectedPlaceType, setSelectedPlaceType, myRequests, kgById, requestToText, createRequest, deactivateRequest, deleteRequest, loading }: { snapshot: PlaygroundSnapshot | null; selectedProfileId: string; selectedPlaceType: string; setSelectedPlaceType: (value: string) => void; myRequests: PlaygroundSnapshot["requests"]; kgById: Map<string, PlaygroundSnapshot["kindergartens"][number]>; requestToText: (requestId: string) => string; createRequest: (data: { fromKgId: string; wantedKgId: string; ageGroup: string }) => void; deactivateRequest: (id: string) => void; deleteRequest: (id: string) => void; loading: boolean }) {
  const [fromKgId, setFromKgId] = useState("");
  const [wantedKgId, setWantedKgId] = useState("");
  const [ageGroup, setAgeGroup] = useState("2019");
  const kindergartens = snapshot?.kindergartens ?? [];

  return <AppSection><PageTitle eyebrow="Нова заявка" title="Къде сте и къде искате да сте?" body="Избери сегашно и желано място. Match-ът работи само между еднакъв тип места." /><section className="rounded-[2.2rem] bg-white/90 p-4 shadow-soft backdrop-blur"><div className="space-y-3 rounded-[1.8rem] bg-paper p-4"><FieldLabel>Имаме място в</FieldLabel><SelectField value={fromKgId} onChange={setFromKgId}><option value="">Избери градина</option>{kindergartens.map((kg) => <option key={kg.id} value={kg.id}>{kg.name} · {kg.district}</option>)}</SelectField><FieldLabel>Желана градина</FieldLabel><SelectField value={wantedKgId} onChange={setWantedKgId}><option value="">Избери желана градина</option>{kindergartens.map((kg) => <option key={kg.id} value={kg.id}>{kg.name} · {kg.district}</option>)}</SelectField><FieldLabel>Набор / група</FieldLabel><input value={ageGroup} onChange={(e) => setAgeGroup(e.target.value)} className="w-full rounded-[1.35rem] bg-white/70 px-4 py-4 text-sm font-bold outline-none" /></div><PlaceTypeSelector value={selectedPlaceType} onChange={setSelectedPlaceType} /><button type="button" disabled={loading || !selectedProfileId || !fromKgId || !wantedKgId} onClick={() => createRequest({ fromKgId, wantedKgId, ageGroup })} className="mt-4 w-full rounded-full bg-orange px-5 py-4 text-sm font-extrabold text-white shadow-soft disabled:opacity-40">Активирай заявка</button><p className="mt-3 text-center text-xs font-medium leading-5 text-ink/45">Заявката ще се скрие автоматично при потенциален цикъл.</p></section><section className="space-y-3"><h2 className="px-1 text-2xl font-extrabold tracking-[-0.04em]">Моите заявки</h2>{myRequests.length ? myRequests.map((r) => <RequestCard key={r.id} text={`${kgById.get(r.from_kindergarten_id)?.name ?? "—"} → ${requestToText(r.id)}`} ageGroup={r.child_group_year_or_age_group} active={r.is_active} locked={r.is_locked} placeType={selectedPlaceType} onDeactivate={() => deactivateRequest(r.id)} onDelete={() => deleteRequest(r.id)} loading={loading} />) : <EmptyCard title="Няма активна заявка" body="Попълни формата горе, за да стартираш търсене на съвпадение." />}</section></AppSection>;
}
